# **IMPORT THE LIBRARIES**


In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.models import Sequential
from keras.layers import Dense

## **LOAD THE DATASET**


In [2]:
dataset = pd.read_csv('/content/drive/MyDrive/House Price India.csv')

# **SEPARATE THE FEATURE AND TARGET VARIABLE**

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [16]:
X

array([[6.76281014e+09, 4.24910000e+04, 5.00000000e+00, ...,
        5.40000000e+03, 2.00000000e+00, 5.80000000e+01],
       [6.76281064e+09, 4.24910000e+04, 4.00000000e+00, ...,
        4.00000000e+03, 2.00000000e+00, 5.10000000e+01],
       [6.76281100e+09, 4.24910000e+04, 5.00000000e+00, ...,
        6.60000000e+03, 1.00000000e+00, 5.30000000e+01],
       ...,
       [6.76283062e+09, 4.27340000e+04, 2.00000000e+00, ...,
        6.12000000e+03, 2.00000000e+00, 6.40000000e+01],
       [6.76283071e+09, 4.27340000e+04, 4.00000000e+00, ...,
        6.63100000e+03, 3.00000000e+00, 5.40000000e+01],
       [6.76283146e+09, 4.27340000e+04, 3.00000000e+00, ...,
        3.48000000e+03, 2.00000000e+00, 5.50000000e+01]])

In [18]:
y

array([2380000, 1400000, 1200000, ...,  209000,  205000,  146000])

# **1. PREPROCESS THE DATASET**

# SPLIT THE DATASET INTO TRAINING AND TESTING DATASE

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()
     

In [5]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)


In [19]:

X_train

array([[-0.89473736, -0.26810979, -0.41264256, ...,  1.60103898,
         1.21026137, -1.56937495],
       [ 0.95616665,  0.79755156,  0.69151379, ...,  0.27844098,
        -0.01360315,  1.23576993],
       [ 1.17771644, -1.3781737 ,  0.69151379, ..., -0.18993916,
        -1.23746766,  1.68459311],
       ...,
       [-1.15867059, -0.49012257, -0.41264256, ..., -0.18368129,
        -0.01360315, -1.45716916],
       [-0.28210403, -1.48177967, -1.51679892, ..., -0.42869785,
        -1.23746766, -0.447317  ],
       [ 0.26550926, -0.07569872, -0.41264256, ..., -0.28515085,
        -1.23746766,  1.57238732]])

In [20]:
X_test

array([[ 1.4333745 , -0.83164801, -2.26540243, ..., -0.42331455,
        -0.02048817,  1.01814492],
       [-0.52188572, -0.75636571, -0.37901863, ..., -0.11027196,
         1.20211187, -0.9757159 ],
       [-0.770479  , -1.58447103, -1.32221053, ..., -0.27740682,
         1.20211187,  0.79660483],
       ...,
       [-1.49106462,  1.24614351,  0.56417327, ..., -0.33633699,
         1.20211187,  0.68583478],
       [ 1.24744778,  0.32769943, -0.37901863, ..., -0.19851395,
        -1.2430882 , -0.9757159 ],
       [-0.95927594, -0.75636571,  1.50736516, ..., -0.09494552,
        -1.2430882 , -0.86494586]])

# **2. BUILD THE ANN MODEL**

In [6]:
# Initialize the ANN model :
model = Sequential()

# A. INPUT LAYER AND B. MINIMUM TWO INPUT HIDDEN LAYERS

In [7]:
# Add the input layer and the first hidden layer :
model.add(Dense(units=10, activation='relu', input_dim=X_train.shape[1]))

# B. MINIMUM TWO INPUT HIDDEN LAYERS

In [8]:
# Add the second hidden layer :
model.add(Dense(units=8, activation='relu'))

# C. ADD THE OUTPUT LAYER

In [9]:
# Add the output layer:
model.add(Dense(units=1, activation='sigmoid'))

In [10]:
# Compile the model:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
     

In [12]:
#TRAIN THE MODEL
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))


Epoch 1/100
366/366 [==============================] - 3s 4ms/step - loss: -9451210.0000 - accuracy: 0.0000e+00 - val_loss: -33919096.0000 - val_accuracy: 0.0000e+00
Epoch 2/100
366/366 [==============================] - 1s 3ms/step - loss: -129822096.0000 - accuracy: 0.0000e+00 - val_loss: -282562880.0000 - val_accuracy: 0.0000e+00
Epoch 3/100
366/366 [==============================] - 1s 3ms/step - loss: -552564352.0000 - accuracy: 0.0000e+00 - val_loss: -923131776.0000 - val_accuracy: 0.0000e+00
Epoch 4/100
366/366 [==============================] - 1s 2ms/step - loss: -1394109312.0000 - accuracy: 0.0000e+00 - val_loss: -2018672512.0000 - val_accuracy: 0.0000e+00
Epoch 5/100
366/366 [==============================] - 1s 2ms/step - loss: -2750095616.0000 - accuracy: 0.0000e+00 - val_loss: -3711211264.0000 - val_accuracy: 0.0000e+00
Epoch 6/100
366/366 [==============================] - 1s 2ms/step - loss: -4695830528.0000 - accuracy: 0.0000e+00 - val_loss: -6006230016.0000 - val_accu

# **3. TEST THE MODEL**

In [13]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

92/92 [==============================] - 0s 1ms/step


# EVALUATE THE MODEL

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
