In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.models import Sequential
from keras.layers import Dense

Load the dataset which is needed

In [2]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [4]:
dataset = pd.read_csv('/content/drive/MyDrive/House Price India.csv')

SEPARATE THE FEATURE AND TARGET VARIABLE

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


1. PREPROCESS THE DATASET


SPLIT THE DATASET INTO TRAINING AND TESTING DATASET

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()
     

In [7]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)


BUILD THE ANN MODEL

In [8]:
# Initialize the ANN model :
model = Sequential()

A. INPUT LAYER AND B. MINIMUM TWO INPUT HIDDEN LAYERS

In [9]:
# Add the input layer and the first hidden layer :
model.add(Dense(units=10, activation='relu', input_dim=X_train.shape[1]))
     

In [10]:
# Add the second hidden layer :
model.add(Dense(units=8, activation='relu'))

C. ADD THE OUTPUT LAYER

In [11]:
# Add the output layer:
model.add(Dense(units=1, activation='sigmoid'))
     

In [13]:
# Compile the model:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


TRAIN THE MODEL


In [15]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))


Epoch 1/100
366/366 [==============================] - 2s 3ms/step - loss: -6188583.0000 - accuracy: 0.0000e+00 - val_loss: -23371084.0000 - val_accuracy: 0.0000e+00
Epoch 2/100
366/366 [==============================] - 1s 2ms/step - loss: -87996656.0000 - accuracy: 0.0000e+00 - val_loss: -193636944.0000 - val_accuracy: 0.0000e+00
Epoch 3/100
366/366 [==============================] - 1s 2ms/step - loss: -384948032.0000 - accuracy: 0.0000e+00 - val_loss: -647995072.0000 - val_accuracy: 0.0000e+00
Epoch 4/100
366/366 [==============================] - 1s 2ms/step - loss: -985456960.0000 - accuracy: 0.0000e+00 - val_loss: -1433987968.0000 - val_accuracy: 0.0000e+00
Epoch 5/100
366/366 [==============================] - 1s 2ms/step - loss: -1954789376.0000 - accuracy: 0.0000e+00 - val_loss: -2645134336.0000 - val_accuracy: 0.0000e+00
Epoch 6/100
366/366 [==============================] - 1s 2ms/step - loss: -3355307520.0000 - accuracy: 0.0000e+00 - val_loss: -4302587904.0000 - val_accura

3. TEST THE MODEL

In [16]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)


92/92 [==============================] - 0s 1ms/step


EVALUATE THE MODEL

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
