**IMPORT THE LIBRARIES**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.models import Sequential
from keras.layers import Dense

**LOAD THE DATASET**

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/NM/House Price India-Assignment-02.csv')

**SEPARATE THE FEATURE AND TARGET VARIABLE**

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

**1. PREPROCESS THE DATASET**

**SPLIT THE DATASET INTO TRAINING AND TESTING DATASET**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

**2. BUILD THE ANN MODEL**

In [ ]:
# Initialize the ANN model :
model = Sequential()

**A. INPUT LAYER AND
B. MINIMUM TWO INPUT HIDDEN LAYERS**

In [ ]:
# Add the input layer and the first hidden layer :
model.add(Dense(units=10, activation='relu', input_dim=X_train.shape[1]))
     
# Add the second hidden layer :
model.add(Dense(units=8, activation='relu'))

**C. ADD THE OUTPUT LAYER**

In [ ]:
# Add the output layer:
model.add(Dense(units=1, activation='sigmoid'))
     
# Compile the model:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

**TRAIN THE MODEL**

In [ ]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
366/366 [==============================] - 2s 3ms/step - loss: -8506279.0000 - accuracy: 0.0000e+00 - val_loss: -35662432.0000 - val_accuracy: 0.0000e+00
Epoch 2/100
366/366 [==============================] - 1s 2ms/step - loss: -154656544.0000 - accuracy: 0.0000e+00 - val_loss: -361288704.0000 - val_accuracy: 0.0000e+00
Epoch 3/100
366/366 [==============================] - 1s 2ms/step - loss: -739485248.0000 - accuracy: 0.0000e+00 - val_loss: -1263332352.0000 - val_accuracy: 0.0000e+00
Epoch 4/100
366/366 [==============================] - 1s 2ms/step - loss: -1985060480.0000 - accuracy: 0.0000e+00 - val_loss: -2919852544.0000 - val_accuracy: 0.0000e+00
Epoch 5/100
366/366 [==============================] - 1s 3ms/step - loss: -3991668736.0000 - accuracy: 0.0000e+00 - val_loss: -5371920896.0000 - val_accuracy: 0.0000e+00
Epoch 6/100
366/366 [==============================] - 1s 3ms/step - loss: -6828767232.0000 - accuracy: 0.0000e+00 - val_loss: -8731094016.0000 - val_acc

**3. TEST THE MODEL**

In [ ]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

92/92 [==============================] - 0s 1ms/step


**EVALUATE THE MODEL**

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
